[build.env]
passthrough = [
    "CARGO_NET_GIT_FETCH_WITH_CLI",
]

[target.aarch64-unknown-linux-gnu]
# Use updated cross image that supports rustls-tls
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.5"